### PR TITLE
[#3] Added Chrome Mink Webdriver trait

### LINKED ISSUE #3: Webdriver trait
We need a webdriver trait as well. :wink:

### PR DESCRIPTION
**Pull request by jibran**
HT: @Eric115 Fixes #3

### CODE REVIEW

**Comment by weitzman** [comment]
Code looks good. I'd love some docs about when to use MinkSetup and when to use WebDriverSetup. Some detail about prerequisites for WebDriverSetup are welcome. You can point to config.yml or other. Also need to document the new DTT_API_URL.

**Comment by weitzman** [comment]
Also, docker-compose.yml should get same changes as Circle.

Sorry, I caused a conflict with a merge just now 😢

**Comment by jibran** [comment]
And we are green also addressed the feedback.

**Comment by weitzman** [comment]
Great work! Thanks @jibran.

I merged after making this work in docker-compose by changing hostname of DTT_BASE_URL. See 88b5f8c

The README needs work. We need to mention the two test types when authoring, and the two base classes. We should do some renaming too. MinkSetup should be GoutteSetup (or Minksetup is an abstract class and both GoutteSetup and WebDriverSetup extend it). Also the names ExampleTest and ExampleFunctionalTest don't quite differentiate each approach. Also need to customize https://github.com/weitzman/drupal-test-traits/blob/master/docs/phpunit.xml for new test type.

**Pull request merged**
